### ISSUE TITLE
cannot find module gulp-rewrite-css

### ISSUE THREAD

**Issue by dishui** [joscha/gulp-rewrite-css#14]
After double checked and reinstalled gulp-rewrite-css, I still can not use it. for some reason, it just can not find gulp-rewrite-css, all the other modules like gulp-uglify et al are all fine. 

 here is the error:

odule.js:340
    throw err;
          ^
Error: Cannot find module 'gulp-rewrite-css'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (gulpfile.js:7:18)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

**Comment by joscha** [comment]
@dishui are you on windows? Could you try if `0.0.5-beta` works for you?

**Comment by aybarshazar** [comment]
I got the same error with 0.0.5-beta. I had to install 0.0.4 to make it work. Other than that, cool plugin!

Btw I'm on OS X.

**Comment by rooks** [comment]
`./lib/index.js` file is missing from package. It looks like `npm prepublish` didn't fire for some reason.

**Comment by joscha** [comment]
please test version `0.0.6`.
